/**
 * ═══════════════════════════════════════════════════════════
 * ASTRO CONFIG — LYRIX DIGITAL
 *
 * Central configuration for the Astro build system.
 *
 * Key decisions:
 * - output: 'static'  → All pages pre-rendered at build time.
 *   The Cloudflare adapter handles the API routes as Functions.
 * - inlineStylesheets: 'always' → CSS inlined in HTML to eliminate
 *   render-blocking stylesheet requests (improves LCP).
 * - manualChunks → Framer Motion and React split into separate
 *   cached bundles so they don't re-download on page changes.
 * - i18n → English default, Spanish supported. Root "/" serves EN
 *   without a /en/ prefix to avoid an extra redirect hop.
 * ═══════════════════════════════════════════════════════════
 */

import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'astro/config';
import cloudflare from '@astrojs/cloudflare';
import partytown from '@astrojs/partytown';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  /* Production domain — used for canonical URLs, sitemap, OG tags */
  site: 'https://lyrixdigital.com',

  /* Static pre-rendering for all pages (SSG). API routes still run
     as Cloudflare Functions via the adapter. */
  output: 'static',

  /* Cloudflare Pages adapter — enables edge deployment + Functions
     for server-side routes like /api/send */
  adapter: cloudflare(),

  build: {
    /* Inline all stylesheets directly into HTML to eliminate
       render-blocking <link> requests (Lighthouse performance win) */
    inlineStylesheets: 'always',
  },

  vite: {
    /* Tailwind CSS v4 uses a Vite plugin instead of PostCSS */
    plugins: [tailwindcss()],
    build: {
      cssCodeSplit: true,
      rollupOptions: {
        output: {
          /* Split heavy libraries into separate chunks for long-term
             caching. Framer Motion (~45KB) and React (~40KB) rarely
             change, so isolating them prevents cache busting. */
          manualChunks: {
            'framer': ['framer-motion'],
            'react-vendor': ['react', 'react-dom'],
          },
        },
      },
    },
  },

  /* ─── Internationalization ───
     English is the default locale (no /en/ prefix at root).
     Spanish is available at /es/. Hreflang alternates are
     generated by SEO.astro for cross-language linking. */
  i18n: {
    defaultLocale: 'en',
    locales: ['es', 'en'],
    routing: {
      prefixDefaultLocale: false,
      redirectToDefaultLocale: true,
    },
  },

  /* ─── Integrations ───
     - react(): Enables React islands (client:idle / client:visible)
     - sitemap(): Auto-generates sitemap-index.xml at build time */
  integrations: [
    react(),
    sitemap(),
    partytown({
      config: {
        forward: ['dataLayer.push'],
      },
    }),
  ],
});